# Example values file for deploying multiple ArmorCode Web Agents
# Each agent will have its own API key

# Common configuration for all agents
agentDefaults:
  # ArmorCode server URL - common for all agents
  serverUrl: https://qa.armorcode.ai
  
  # Enable debug mode
  debugMode: true
  
  # Request timeout in seconds
  timeout: 30
  
  # Whether to verify SSL certificates
  verify: false
  
  # Thread pool size
  poolSize: 5
  
  # Whether to upload directly to ArmorCode
  uploadToAc: true

# Turn off single deployment mode
singleDeployment:
  enabled: false

# Enable multiple deployments mode
multipleDeployments:
  enabled: true
  
  # List of deployments with unique names and API keys
  instances:
    # First agent - Production environment
    - name: prod
      apiKey:
      envName: production
      
    # Second agent - Staging environment  
    - name: staging
      apiKey:
      envName: staging
      
    # Third agent - Development environment
    - name: dev
      apiKey:
      envName: development

# Use local built image
image:
  repository: armorcode-web-agent
  tag: local
  pullPolicy: Never  # Never pull from registry, use local image only

# Disable persistence for this example
persistence:
  enabled: false

# Network policy configuration
networkPolicy:
  enabled: true
  spec:
    podSelector:
      matchLabels:
        app.kubernetes.io/name: armorcode-web-agent
    policyTypes:
      - Egress
    egress:
      # Allow DNS resolution
      - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        ports:
          - port: 53
            protocol: UDP
          - port: 53
            protocol: TCP
      
      # Allow HTTPS to all external destinations
      - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        ports:
          - port: 443
            protocol: TCP
