name: PRs to main
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  merge-main-back-to-qa:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'qa'
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.JENKINS_TOKEN }}
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge main back to qa
        run: |
          git fetch --unshallow
          git checkout qa
          git pull
          git merge --no-ff origin/main -m "Auto-merge main back to qa"
          git push